# Generated by Django 2.0 on 2018-02-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0004_auto_20180204_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('语篇编号', models.CharField(max_length=50)),
                ('语篇内容', models.TextField()),
                ('领域', models.CharField(choices=[('jy', '教育'), ('zc', '职场'), ('gg', '公共'), ('gr', '个人')], max_length=50)),
                ('文本体裁', models.CharField(choices=[('ylw', '议论文'), ('smw', '说明文'), ('jxw', '记叙文'), ('msw', '描述文')], max_length=50)),
                ('文本类型', models.CharField(choices=[('db', '独白'), ('dh', '对话'), ('tl', '讨论')], max_length=50)),
                ('素材真实性', models.CharField(choices=[('zsyp', '真实语篇'), ('gbyp', '改编语篇')], max_length=50)),
                ('文本字数', models.IntegerField()),
                ('平均音节数', models.FloatField()),
                ('词元数', models.IntegerField()),
                ('词族数', models.IntegerField()),
                ('通用词汇占比', models.FloatField()),
                ('学术词汇占比', models.FloatField()),
                ('专业词汇占比', models.FloatField()),
                ('音频类型', models.CharField(max_length=10)),
                ('音频完整时长', models.FloatField()),
                ('音频真实说话时长', models.FloatField()),
                ('语速', models.IntegerField()),
                ('语速分档', models.CharField(choices=[('ks', '快速'), ('jk', '较快'), ('zs', '中速'), ('jm', '较慢'), ('ms', '慢速')], max_length=20)),
                ('口音', models.CharField(choices=[('my', '美音'), ('yy', '英音'), ('adly', '澳大利亚'), ('jnd', '加拿大')], max_length=50)),
                ('从属子句数', models.IntegerField()),
                ('T单位数量', models.IntegerField()),
                ('小句数量', models.IntegerField()),
                ('话题熟悉度', models.CharField(max_length=20)),
                ('是否包含图表辅助信息', models.CharField(choices=[('0', '否'), ('1', '是')], max_length=10)),
                ('句子数量', models.IntegerField()),
                ('平均词数', models.FloatField()),
                ('文本可读性指标', models.FloatField()),
                ('语篇标注人', models.CharField(max_length=50)),
                ('语篇标注状态', models.CharField(choices=[('wbz', '未标注'), ('dxg', '待修改'), ('ybz', '已标注')], max_length=20)),
                ('语篇评审人', models.CharField(max_length=50)),
                ('语篇评审状态', models.CharField(choices=[('wps', '未评审'), ('wtg', '评审未通过'), ('tg', '评审通过')], max_length=20)),
                ('语篇评审未通过原因', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('题目编号', models.CharField(max_length=50)),
                ('问题序号', models.CharField(max_length=10)),
                ('content_level_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_c1', to='label.Label', verbose_name='内容一级标签')),
                ('content_level_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_c2', to='label.Label', verbose_name='内容二级标签')),
                ('skill_level_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_s1', to='label.Label', verbose_name='微技能一级标签')),
                ('skill_level_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_s2', to='label.Label', verbose_name='微技能二级标签')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('平台名称', models.CharField(choices=[('itest', 'itest'), ('ucampus', 'u校园'), ('u2', 'u2')], max_length=20)),
                ('题目编号', models.CharField(max_length=50)),
                ('题目详细路径', models.CharField(max_length=50)),
                ('题目类型', models.CharField(choices=[('tk', '题库'), ('jcptxt', '教材配套习题')], max_length=20)),
                ('题目对应教材', models.CharField(max_length=100)),
                ('题目对应分类', models.CharField(choices=[('tl', '听力'), ('yd', '阅读'), ('xz', '写作'), ('ky', '口语')], max_length=20)),
                ('题目内容', models.TextField()),
                ('题目详情页地址', models.CharField(max_length=300)),
                ('音频存放地址', models.CharField(max_length=100)),
                ('题目版本', models.CharField(max_length=20)),
                ('语篇编号', models.CharField(max_length=50)),
                ('题目所处区域ID', models.CharField(max_length=100)),
                ('微技能标注人', models.CharField(max_length=50)),
                ('微技能标注状态', models.CharField(choices=[('wbz', '未标注'), ('dxg', '待修改'), ('ybz', '已标注')], max_length=20)),
                ('微技能评审人', models.CharField(max_length=50)),
                ('微技能评审状态', models.CharField(choices=[('wps', '未评审'), ('pswtg', '评审未通过'), ('pstg', '评审通过')], max_length=20)),
                ('微技能评审未通过原因', models.CharField(max_length=500)),
                ('教程id', models.CharField(max_length=255)),
                ('教程名称', models.CharField(max_length=100)),
                ('单元id', models.CharField(max_length=255)),
                ('单元名称', models.CharField(max_length=100)),
                ('微课id', models.CharField(max_length=255)),
                ('微课名称', models.CharField(max_length=100)),
                ('taskid', models.CharField(max_length=255)),
            ],
        ),
    ]
