# Generated by Django 2.0 on 2018-02-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_rate', models.FloatField(null=True)),
                ('adjectival_clause_num', models.IntegerField(null=True)),
                ('adverbial_clauses_num', models.IntegerField(null=True)),
                ('avg_syllable_num', models.FloatField(null=True)),
                ('avg_words_per_sent', models.FloatField(null=True)),
                ('common_rate', models.FloatField(null=True)),
                ('compound_sent_adversative_num', models.IntegerField(null=True)),
                ('compound_sent_select_num', models.IntegerField(null=True)),
                ('compound_sent_semantic_exten_num', models.IntegerField(null=True)),
                ('discourse', models.CharField(max_length=5000, null=True)),
                ('discourse_code', models.CharField(max_length=50, null=True)),
                ('discourse_review_user', models.CharField(max_length=50, null=True)),
                ('discourse_tag_user', models.CharField(max_length=50, null=True)),
                ('family_num', models.IntegerField(null=True)),
                ('lemma_num', models.IntegerField(null=True)),
                ('ls_activity_type', models.CharField(max_length=50, null=True)),
                ('ls_audio_all_time', models.FloatField(default=0)),
                ('ls_audio_real_time', models.FloatField(null=True)),
                ('ls_audio_type', models.CharField(max_length=20, null=True)),
                ('ls_authenticity', models.CharField(max_length=50, null=True)),
                ('ls_domain', models.CharField(max_length=50, null=True)),
                ('ls_genre', models.CharField(max_length=50, null=True)),
                ('ls_speed', models.IntegerField(null=True)),
                ('ls_speed_syllable', models.FloatField(null=True)),
                ('ls_speed_type', models.CharField(max_length=20, null=True)),
                ('ls_voice_type', models.CharField(max_length=50, null=True)),
                ('noun_clauses_num', models.IntegerField(null=True)),
                ('re_domain', models.CharField(max_length=50, null=True)),
                ('re_familiarity', models.IntegerField(null=True)),
                ('re_flesch_kincaid_grade_level', models.FloatField(null=True)),
                ('re_genre', models.CharField(max_length=50, null=True)),
                ('re_is_chart', models.CharField(max_length=10, null=True)),
                ('review_fail_reason', models.CharField(max_length=1000, null=True)),
                ('review_status', models.CharField(max_length=20, null=True)),
                ('sentence_num', models.IntegerField(null=True)),
                ('tag_status', models.CharField(max_length=20, null=True)),
                ('word_num', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'discourse_quata',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ident', models.CharField(max_length=50, null=True, verbose_name='题目编号')),
                ('question_index', models.IntegerField()),
                ('content_level_1', models.CharField(max_length=10, null=True, verbose_name='内容一级标签')),
                ('content_level_2', models.CharField(max_length=10, null=True, verbose_name='内容二级标签')),
                ('skill_level_1', models.CharField(max_length=10, null=True, verbose_name='微技能一级标签')),
                ('skill_level_2', models.CharField(max_length=10, null=True, verbose_name='微技能二级标签')),
            ],
            options={
                'db_table': 'question_detail',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('itest', 'itest'), ('ucampus', 'u校园'), ('u2', 'u2')], max_length=200, null=True, verbose_name='平台名称')),
                ('title_ident', models.CharField(max_length=500, null=True, verbose_name='题目编号')),
                ('title_detail_path', models.CharField(max_length=2000, null=True, verbose_name='题目详细路径')),
                ('title_type', models.CharField(choices=[('tk', '题库'), ('jcptxt', '教材配套习题')], max_length=200, null=True, verbose_name='题目类型')),
                ('title_course', models.CharField(max_length=1000, null=True, verbose_name='题目对应教材')),
                ('title_category', models.CharField(choices=[('tl', '听力'), ('yd', '阅读'), ('xz', '写作'), ('ky', '口语')], max_length=200, null=True, verbose_name='题目对应分类')),
                ('title_info', models.TextField(null=True, verbose_name='题目内容')),
                ('title_url', models.CharField(max_length=5000, null=True, verbose_name='题目详情页地址')),
                ('video_path', models.CharField(max_length=1000, null=True, verbose_name='音频存放地址')),
                ('version', models.CharField(max_length=1000, null=True, verbose_name='题目版本')),
                ('discourse_code', models.CharField(max_length=500, null=True, verbose_name='语篇编号')),
                ('block_id', models.CharField(max_length=1000, null=True, verbose_name='题目所处区域ID')),
                ('label_tag_user', models.CharField(max_length=500, null=True, verbose_name='微技能标注人')),
                ('label_tag_status', models.CharField(choices=[('wbz', '未标注'), ('dxg', '待修改'), ('ybz', '已标注')], max_length=200, null=True, verbose_name='微技能标注状态')),
                ('label_review_user', models.CharField(max_length=500, null=True, verbose_name='微技能评审人')),
                ('label_review_status', models.CharField(choices=[('wps', '未评审'), ('pswtg', '评审未通过'), ('pstg', '评审通过')], max_length=200, null=True, verbose_name='微技能评审状态')),
                ('review_fail_reason', models.CharField(max_length=5000, null=True, verbose_name='微技能评审未通过原因')),
                ('tutorial_id', models.CharField(max_length=2550, null=True, verbose_name='教程id')),
                ('tutorial_name', models.CharField(max_length=1000, null=True, verbose_name='教程名称')),
                ('unit_id', models.CharField(max_length=2550, null=True, verbose_name='单元id')),
                ('unit_name', models.CharField(max_length=1000, null=True, verbose_name='单元名称')),
                ('minicoz_id', models.CharField(max_length=2550, null=True, verbose_name='微课id')),
                ('minicoz_name', models.CharField(max_length=1000, null=True, verbose_name='微课名称')),
                ('task_id', models.CharField(max_length=2550, null=True, verbose_name='taskid')),
            ],
            options={
                'db_table': 'title_bank',
            },
        ),
    ]
