# Generated by Django 2.0 on 2018-02-04 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discourse',
            name='T单位数量',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='专业词汇占比',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='从属子句数',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='口音',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='句子数量',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='学术词汇占比',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='小句数量',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='平均词数',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='平均音节数',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='文本体裁',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='文本可读性指标',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='文本字数',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='文本类型',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='是否包含图表辅助信息',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='素材真实性',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='词元数',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='词族数',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='话题熟悉度',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语篇内容',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语篇标注人',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语篇标注状态',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语篇编号',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语篇评审人',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语篇评审未通过原因',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语篇评审状态',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语速',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='语速分档',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='通用词汇占比',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='音频完整时长',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='音频真实说话时长',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='音频类型',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='领域',
        ),
        migrations.RemoveField(
            model_name='question',
            name='问题序号',
        ),
        migrations.RemoveField(
            model_name='question',
            name='题目编号',
        ),
        migrations.RemoveField(
            model_name='title',
            name='taskid',
        ),
        migrations.RemoveField(
            model_name='title',
            name='单元id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='单元名称',
        ),
        migrations.RemoveField(
            model_name='title',
            name='平台名称',
        ),
        migrations.RemoveField(
            model_name='title',
            name='微技能标注人',
        ),
        migrations.RemoveField(
            model_name='title',
            name='微技能标注状态',
        ),
        migrations.RemoveField(
            model_name='title',
            name='微技能评审人',
        ),
        migrations.RemoveField(
            model_name='title',
            name='微技能评审未通过原因',
        ),
        migrations.RemoveField(
            model_name='title',
            name='微技能评审状态',
        ),
        migrations.RemoveField(
            model_name='title',
            name='微课id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='微课名称',
        ),
        migrations.RemoveField(
            model_name='title',
            name='教程id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='教程名称',
        ),
        migrations.RemoveField(
            model_name='title',
            name='语篇编号',
        ),
        migrations.RemoveField(
            model_name='title',
            name='音频存放地址',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目内容',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目对应分类',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目对应教材',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目所处区域ID',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目版本',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目类型',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目编号',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目详情页地址',
        ),
        migrations.RemoveField(
            model_name='title',
            name='题目详细路径',
        ),
        migrations.AddField(
            model_name='discourse',
            name='academic_rate',
            field=models.FloatField(default=0, verbose_name='学术词汇占比'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='audio_all_time',
            field=models.FloatField(default=0, verbose_name='音频完整时长'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='audio_real_time',
            field=models.FloatField(default=0, verbose_name='音频真实说话时长'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='audio_type',
            field=models.CharField(default='', max_length=10, verbose_name='音频类型'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='authenticity',
            field=models.CharField(choices=[('zsyp', '真实语篇'), ('gbyp', '改编语篇')], max_length=50, null=True, verbose_name='素材真实性'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='avg_syllable_num',
            field=models.FloatField(default=0, verbose_name='平均音节数'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='avg_words_per_sent',
            field=models.FloatField(default=0, verbose_name='平均词数'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='clause_num',
            field=models.IntegerField(default=0, verbose_name='小句数量'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='common_rate',
            field=models.FloatField(default=0, verbose_name='通用词汇占比'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='discourse',
            field=models.TextField(default='', verbose_name='语篇内容'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='discourse_code',
            field=models.CharField(default='', max_length=50, verbose_name='语篇编号'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='discourse_review_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_discourses', to=settings.AUTH_USER_MODEL, verbose_name='语篇评审人'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='discourse_tag_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taged_discourses', to=settings.AUTH_USER_MODEL, verbose_name='语篇标注人'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='domain',
            field=models.CharField(choices=[('jy', '教育'), ('zc', '职场'), ('gg', '公共'), ('gr', '个人')], max_length=50, null=True, verbose_name='领域'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='familiarity',
            field=models.CharField(default='', max_length=20, verbose_name='话题熟悉度'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='family_num',
            field=models.IntegerField(default=0, verbose_name='词族数'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='flesch_kincaid_grade_level',
            field=models.FloatField(default=0, verbose_name='文本可读性指标'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='genre',
            field=models.CharField(choices=[('ylw', '议论文'), ('smw', '说明文'), ('jxw', '记叙文'), ('msw', '描述文')], max_length=50, null=True, verbose_name='文本体裁'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='indep_clause_num',
            field=models.IntegerField(default=0, verbose_name='从属子句数'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='is_chart',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=10, verbose_name='是否包含图表辅助信息'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='lemma_num',
            field=models.IntegerField(default=0, verbose_name='词元数'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='major_rate',
            field=models.FloatField(default=0, verbose_name='专业词汇占比'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='review_fail_reason',
            field=models.CharField(max_length=500, null=True, verbose_name='语篇评审未通过原因'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='review_status',
            field=models.CharField(choices=[('wps', '未评审'), ('wtg', '评审未通过'), ('tg', '评审通过')], max_length=20, null=True, verbose_name='语篇评审状态'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='sentence_num',
            field=models.IntegerField(default=0, verbose_name='句子数量'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='语速'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='speed_type',
            field=models.CharField(choices=[('ks', '快速'), ('jk', '较快'), ('zs', '中速'), ('jm', '较慢'), ('ms', '慢速')], max_length=20, null=True, verbose_name='语速分档'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='t_num',
            field=models.IntegerField(default=0, verbose_name='T单位数量'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='tag_status',
            field=models.CharField(choices=[('wbz', '未标注'), ('dxg', '待修改'), ('ybz', '已标注')], max_length=20, null=True, verbose_name='语篇标注状态'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='text_type',
            field=models.CharField(choices=[('db', '独白'), ('dh', '对话'), ('tl', '讨论')], max_length=50, null=True, verbose_name='文本类型'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='voice_type',
            field=models.CharField(choices=[('my', '美音'), ('yy', '英音'), ('adly', '澳大利亚'), ('jnd', '加拿大')], max_length=50, null=True, verbose_name='口音'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='word_num',
            field=models.IntegerField(default=0, verbose_name='文本字数'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_index',
            field=models.CharField(max_length=10, null=True, verbose_name='问题序号'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ident',
            field=models.CharField(max_length=50, null=True, verbose_name='题目编号'),
        ),
        migrations.AddField(
            model_name='title',
            name='block_id',
            field=models.CharField(max_length=100, null=True, verbose_name='题目所处区域ID'),
        ),
        migrations.AddField(
            model_name='title',
            name='discourse_code',
            field=models.CharField(max_length=50, null=True, verbose_name='语篇编号'),
        ),
        migrations.AddField(
            model_name='title',
            name='label_review_status',
            field=models.CharField(choices=[('wps', '未评审'), ('pswtg', '评审未通过'), ('pstg', '评审通过')], max_length=20, null=True, verbose_name='微技能评审状态'),
        ),
        migrations.AddField(
            model_name='title',
            name='label_review_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_titles', to=settings.AUTH_USER_MODEL, verbose_name='微技能评审人'),
        ),
        migrations.AddField(
            model_name='title',
            name='label_tag_status',
            field=models.CharField(choices=[('wbz', '未标注'), ('dxg', '待修改'), ('ybz', '已标注')], max_length=20, null=True, verbose_name='微技能标注状态'),
        ),
        migrations.AddField(
            model_name='title',
            name='label_tag_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taged_titles', to=settings.AUTH_USER_MODEL, verbose_name='微技能标注人'),
        ),
        migrations.AddField(
            model_name='title',
            name='minicoz_id',
            field=models.CharField(max_length=255, null=True, verbose_name='微课id'),
        ),
        migrations.AddField(
            model_name='title',
            name='minicoz_name',
            field=models.CharField(max_length=100, null=True, verbose_name='微课名称'),
        ),
        migrations.AddField(
            model_name='title',
            name='platform',
            field=models.CharField(choices=[('itest', 'itest'), ('ucampus', 'u校园'), ('u2', 'u2')], max_length=20, null=True, verbose_name='平台名称'),
        ),
        migrations.AddField(
            model_name='title',
            name='review_fail_reason',
            field=models.CharField(max_length=500, null=True, verbose_name='微技能评审未通过原因'),
        ),
        migrations.AddField(
            model_name='title',
            name='task_id',
            field=models.CharField(max_length=255, null=True, verbose_name='taskid'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_category',
            field=models.CharField(choices=[('tl', '听力'), ('yd', '阅读'), ('xz', '写作'), ('ky', '口语')], max_length=20, null=True, verbose_name='题目对应分类'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_course',
            field=models.CharField(max_length=100, null=True, verbose_name='题目对应教材'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_detail_path',
            field=models.CharField(max_length=50, null=True, verbose_name='题目详细路径'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_ident',
            field=models.CharField(max_length=50, null=True, verbose_name='题目编号'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_info',
            field=models.TextField(null=True, verbose_name='题目内容'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_type',
            field=models.CharField(choices=[('tk', '题库'), ('jcptxt', '教材配套习题')], max_length=20, null=True, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_url',
            field=models.CharField(max_length=300, null=True, verbose_name='题目详情页地址'),
        ),
        migrations.AddField(
            model_name='title',
            name='tutorial_id',
            field=models.CharField(max_length=255, null=True, verbose_name='教程id'),
        ),
        migrations.AddField(
            model_name='title',
            name='tutorial_name',
            field=models.CharField(max_length=100, null=True, verbose_name='教程名称'),
        ),
        migrations.AddField(
            model_name='title',
            name='unit_id',
            field=models.CharField(max_length=255, null=True, verbose_name='单元id'),
        ),
        migrations.AddField(
            model_name='title',
            name='unit_name',
            field=models.CharField(max_length=100, null=True, verbose_name='单元名称'),
        ),
        migrations.AddField(
            model_name='title',
            name='version',
            field=models.CharField(max_length=20, null=True, verbose_name='题目版本'),
        ),
        migrations.AddField(
            model_name='title',
            name='video_path',
            field=models.CharField(max_length=100, null=True, verbose_name='音频存放地址'),
        ),
    ]
