# Generated by Django 2.0 on 2018-02-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20180204_1159'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discourse',
            table='discourse_quata',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question_detail',
        ),
        migrations.AlterModelTable(
            name='title',
            table='title_bank',
        ),
    ]
