# Generated by Django 2.0 on 2018-02-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20180206_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discourse',
            name='discourse_review_user',
            field=models.CharField(max_length=50, null=True, verbose_name='语篇评审人'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse_tag_user',
            field=models.CharField(max_length=50, null=True, verbose_name='语篇标注人'),
        ),
        migrations.AlterField(
            model_name='title',
            name='label_review_user',
            field=models.CharField(max_length=50, null=True, verbose_name='微技能评审人'),
        ),
        migrations.AlterField(
            model_name='title',
            name='label_tag_user',
            field=models.CharField(max_length=50, null=True, verbose_name='微技能标注人'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_detail_path',
            field=models.CharField(max_length=200, null=True, verbose_name='题目详细路径'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_url',
            field=models.CharField(max_length=500, null=True, verbose_name='题目详情页地址'),
        ),
        migrations.AlterField(
            model_name='title',
            name='version',
            field=models.CharField(max_length=100, null=True, verbose_name='题目版本'),
        ),
    ]
