# Generated by Django 2.0 on 2018-02-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20180206_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content_level_1',
            field=models.ForeignKey(db_column='content_level_1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_c1', to='label.Label', verbose_name='内容一级标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_level_2',
            field=models.ForeignKey(db_column='content_level_2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_c2', to='label.Label', verbose_name='内容二级标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill_level_1',
            field=models.ForeignKey(db_column='skill_level_1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_s1', to='label.Label', verbose_name='微技能一级标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill_level_2',
            field=models.ForeignKey(db_column='skill_level_2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_s2', to='label.Label', verbose_name='微技能二级标签'),
        ),
        migrations.AlterField(
            model_name='title',
            name='video_path',
            field=models.CharField(max_length=300, null=True, verbose_name='音频存放地址'),
        ),
    ]
