# Generated by Django 2.0 on 2018-02-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20180208_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content_level_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_c1', to='label.Label', verbose_name='内容一级标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_level_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_c2', to='label.Label', verbose_name='内容二级标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill_level_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_s1', to='label.Label', verbose_name='微技能一级标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill_level_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_s2', to='label.Label', verbose_name='微技能二级标签'),
        ),
        migrations.AlterField(
            model_name='title',
            name='block_id',
            field=models.CharField(max_length=1000, null=True, verbose_name='题目所处区域ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='discourse_code',
            field=models.CharField(max_length=500, null=True, verbose_name='语篇编号'),
        ),
        migrations.AlterField(
            model_name='title',
            name='label_review_status',
            field=models.CharField(choices=[('wps', '未评审'), ('pswtg', '评审未通过'), ('pstg', '评审通过')], max_length=200, null=True, verbose_name='微技能评审状态'),
        ),
        migrations.AlterField(
            model_name='title',
            name='label_review_user',
            field=models.CharField(max_length=500, null=True, verbose_name='微技能评审人'),
        ),
        migrations.AlterField(
            model_name='title',
            name='label_tag_status',
            field=models.CharField(choices=[('wbz', '未标注'), ('dxg', '待修改'), ('ybz', '已标注')], max_length=200, null=True, verbose_name='微技能标注状态'),
        ),
        migrations.AlterField(
            model_name='title',
            name='label_tag_user',
            field=models.CharField(max_length=500, null=True, verbose_name='微技能标注人'),
        ),
        migrations.AlterField(
            model_name='title',
            name='minicoz_id',
            field=models.CharField(max_length=2550, null=True, verbose_name='微课id'),
        ),
        migrations.AlterField(
            model_name='title',
            name='minicoz_name',
            field=models.CharField(max_length=1000, null=True, verbose_name='微课名称'),
        ),
        migrations.AlterField(
            model_name='title',
            name='platform',
            field=models.CharField(choices=[('itest', 'itest'), ('ucampus', 'u校园'), ('u2', 'u2')], max_length=200, null=True, verbose_name='平台名称'),
        ),
        migrations.AlterField(
            model_name='title',
            name='review_fail_reason',
            field=models.CharField(max_length=5000, null=True, verbose_name='微技能评审未通过原因'),
        ),
        migrations.AlterField(
            model_name='title',
            name='task_id',
            field=models.CharField(max_length=2550, null=True, verbose_name='taskid'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_category',
            field=models.CharField(choices=[('tl', '听力'), ('yd', '阅读'), ('xz', '写作'), ('ky', '口语')], max_length=200, null=True, verbose_name='题目对应分类'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_course',
            field=models.CharField(max_length=1000, null=True, verbose_name='题目对应教材'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_detail_path',
            field=models.CharField(max_length=2000, null=True, verbose_name='题目详细路径'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_ident',
            field=models.CharField(max_length=500, null=True, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.CharField(choices=[('tk', '题库'), ('jcptxt', '教材配套习题')], max_length=200, null=True, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_url',
            field=models.CharField(max_length=5000, null=True, verbose_name='题目详情页地址'),
        ),
        migrations.AlterField(
            model_name='title',
            name='tutorial_id',
            field=models.CharField(max_length=2550, null=True, verbose_name='教程id'),
        ),
        migrations.AlterField(
            model_name='title',
            name='tutorial_name',
            field=models.CharField(max_length=1000, null=True, verbose_name='教程名称'),
        ),
        migrations.AlterField(
            model_name='title',
            name='unit_id',
            field=models.CharField(max_length=2550, null=True, verbose_name='单元id'),
        ),
        migrations.AlterField(
            model_name='title',
            name='unit_name',
            field=models.CharField(max_length=1000, null=True, verbose_name='单元名称'),
        ),
        migrations.AlterField(
            model_name='title',
            name='version',
            field=models.CharField(max_length=1000, null=True, verbose_name='题目版本'),
        ),
        migrations.AlterField(
            model_name='title',
            name='video_path',
            field=models.CharField(max_length=1000, null=True, verbose_name='音频存放地址'),
        ),
    ]
