# Generated by Django 2.0 on 2018-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20180208_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discourse',
            name='audio_all_time',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='audio_real_time',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='audio_type',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='authenticity',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='clause_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='familiarity',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='flesch_kincaid_grade_level',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='indep_clause_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='is_chart',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='major_rate',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='speed_type',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='t_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='text_type',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='voice_type',
        ),
        migrations.AddField(
            model_name='discourse',
            name='adjectival_clause_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='adverbial_clauses_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='compound_sent_adversative_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='compound_sent_select_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='compound_sent_semantic_exten_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_activity_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_audio_all_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_audio_real_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_audio_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_authenticity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_speed_syllable',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_speed_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='ls_voice_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='noun_clauses_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='re_domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='re_familiarity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='re_flesch_kincaid_grade_level',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='re_genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discourse',
            name='re_is_chart',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='academic_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='avg_syllable_num',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='avg_words_per_sent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='common_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse_review_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse_tag_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='family_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='lemma_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='review_fail_reason',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='review_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='sentence_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='tag_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='word_num',
            field=models.IntegerField(null=True),
        ),
    ]
