# Generated by Django 2.0 on 2018-02-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20180208_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discourse',
            name='adjectival_clause_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='adverbial_clauses_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='compound_sent_adversative_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='compound_sent_select_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='compound_sent_semantic_exten_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_activity_type',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_audio_all_time',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_audio_real_time',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_audio_type',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_authenticity',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_domain',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_genre',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_speed',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_speed_syllable',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_speed_type',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='ls_voice_type',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='noun_clauses_num',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='re_domain',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='re_familiarity',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='re_flesch_kincaid_grade_level',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='re_genre',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='re_is_chart',
        ),
        migrations.AddField(
            model_name='discourse',
            name='audio_all_time',
            field=models.FloatField(default=0, verbose_name='音频完整时长'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='audio_real_time',
            field=models.FloatField(default=0, verbose_name='音频真实说话时长'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='audio_type',
            field=models.CharField(default='', max_length=10, verbose_name='音频类型'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='authenticity',
            field=models.CharField(choices=[('zsyp', '真实语篇'), ('gbyp', '改编语篇')], max_length=50, null=True, verbose_name='素材真实性'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='clause_num',
            field=models.IntegerField(default=0, verbose_name='小句数量'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='domain',
            field=models.CharField(choices=[('jy', '教育'), ('zc', '职场'), ('gg', '公共'), ('gr', '个人')], max_length=50, null=True, verbose_name='领域'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='familiarity',
            field=models.CharField(default='', max_length=20, verbose_name='话题熟悉度'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='flesch_kincaid_grade_level',
            field=models.FloatField(default=0, verbose_name='文本可读性指标'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='genre',
            field=models.CharField(choices=[('ylw', '议论文'), ('smw', '说明文'), ('jxw', '记叙文'), ('msw', '描述文')], max_length=50, null=True, verbose_name='文本体裁'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='indep_clause_num',
            field=models.IntegerField(default=0, verbose_name='从属子句数'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='is_chart',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=10, verbose_name='是否包含图表辅助信息'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='major_rate',
            field=models.FloatField(default=0, verbose_name='专业词汇占比'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='语速'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='speed_type',
            field=models.CharField(choices=[('ks', '快速'), ('jk', '较快'), ('zs', '中速'), ('jm', '较慢'), ('ms', '慢速')], max_length=20, null=True, verbose_name='语速分档'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='t_num',
            field=models.IntegerField(default=0, verbose_name='T单位数量'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='text_type',
            field=models.CharField(choices=[('db', '独白'), ('dh', '对话'), ('tl', '讨论')], max_length=50, null=True, verbose_name='文本类型'),
        ),
        migrations.AddField(
            model_name='discourse',
            name='voice_type',
            field=models.CharField(choices=[('my', '美音'), ('yy', '英音'), ('adly', '澳大利亚'), ('jnd', '加拿大')], max_length=50, null=True, verbose_name='口音'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='academic_rate',
            field=models.FloatField(default=0, verbose_name='学术词汇占比'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='avg_syllable_num',
            field=models.FloatField(default=0, verbose_name='平均音节数'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='avg_words_per_sent',
            field=models.FloatField(default=0, verbose_name='平均词数'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='common_rate',
            field=models.FloatField(default=0, verbose_name='通用词汇占比'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse',
            field=models.TextField(default='', verbose_name='语篇内容'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse_code',
            field=models.CharField(default='', max_length=50, verbose_name='语篇编号'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse_review_user',
            field=models.CharField(max_length=50, null=True, verbose_name='语篇评审人'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='discourse_tag_user',
            field=models.CharField(max_length=50, null=True, verbose_name='语篇标注人'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='family_num',
            field=models.IntegerField(default=0, verbose_name='词族数'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='lemma_num',
            field=models.IntegerField(default=0, verbose_name='词元数'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='review_fail_reason',
            field=models.CharField(max_length=500, null=True, verbose_name='语篇评审未通过原因'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='review_status',
            field=models.CharField(choices=[('wps', '未评审'), ('wtg', '评审未通过'), ('tg', '评审通过')], max_length=20, null=True, verbose_name='语篇评审状态'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='sentence_num',
            field=models.IntegerField(default=0, verbose_name='句子数量'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='tag_status',
            field=models.CharField(choices=[('wbz', '未标注'), ('dxg', '待修改'), ('ybz', '已标注')], max_length=20, null=True, verbose_name='语篇标注状态'),
        ),
        migrations.AlterField(
            model_name='discourse',
            name='word_num',
            field=models.IntegerField(default=0, verbose_name='文本字数'),
        ),
    ]
