export const ADD_LABEL = 'ADD_LABEL'
export const MODIFY_LABEL = 'MODIFY_LABEL'
export const DELETE_LABEL = 'DELETE_LABEL'

export const FETCH_TITLES = 'FETCH_TITLES'

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const MODIFY_QUESTIONS = 'MODIFY_QUESTIONS'

export const FETCH_DISCOURSE = 'FETCH_DISCOURSE'
export const MODIFY_DISCOURSE = 'MODIFY_DISCOURSE'

export const FETCH_TITLE = 'FETCH_TITLE'
export const MODIFY_TITLE = 'MODIFY_TITLE'

export const UPDATE_SFFs = 'UPDATE_SEARCH_FORM_FIELDS'
export const FIELD_ON_SEARCH = 'FIELD_ON_SEARCH'
export const FIELD_ON_CHANGE = 'FIELD_ON_CHANGE'
export const FIELD_SEARCH_FINISHED = 'FIELD_SEARCH_FINISHED'
