# Generated by Django 2.0 on 2018-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50, verbose_name='名称')),
                ('parent_id', models.IntegerField(verbose_name='父标签ID')),
                ('label_level', models.IntegerField(verbose_name='标签级别')),
                ('skill_type', models.CharField(max_length=20, verbose_name='技能分类')),
                ('label_type', models.CharField(max_length=10, verbose_name='标签分类')),
            ],
        ),
    ]
