# Generated by Django 2.0 on 2018-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_type',
            field=models.CharField(choices=[('0', '微技能'), ('1', '内容框架')], max_length=10, verbose_name='标签分类'),
        ),
        migrations.AlterField(
            model_name='label',
            name='skill_type',
            field=models.CharField(choices=[('tl', '听力'), ('yd', '阅读'), ('xz', '写作'), ('ky', '口语')], max_length=20, verbose_name='技能分类'),
        ),
    ]
