# Generated by Django 2.0 on 2018-02-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_auto_20180114_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='label',
            name='label_type',
            field=models.CharField(choices=[('WJN', '微技能'), ('NRKJ', '内容框架')], max_length=10, verbose_name='标签分类'),
        ),
        migrations.AlterField(
            model_name='label',
            name='skill_type',
            field=models.CharField(choices=[('TL', '听力'), ('YD', '阅读'), ('XZ', '写作'), ('KY', '口语')], max_length=20, verbose_name='技能分类'),
        ),
    ]
