# Generated by Django 2.0 on 2018-02-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_auto_20180204_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_ch_name',
            field=models.CharField(default='', max_length=100, verbose_name='课程中文名称'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='课程ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=100, verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='course',
            name='unit_num',
            field=models.IntegerField(default=10, verbose_name='单元数量'),
        ),
    ]
