# Generated by Django 2.0 on 2018-02-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_auto_20180205_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(db_column='course_id', default='', max_length=100, primary_key=True, serialize=False, verbose_name='课程ID'),
        ),
    ]
