# Generated by Django 2.0 on 2018-02-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_auto_20180205_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_ch_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(db_column='course_name', default='', max_length=100, verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_zh',
            field=models.CharField(db_column='course_ch_name', default='', max_length=100, verbose_name='课程中文名称'),
        ),
    ]
