# Generated by Django 2.0 on 2018-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('label', '0007_auto_20180205_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='label_level',
        ),
        migrations.RemoveField(
            model_name='label',
            name='label_name',
        ),
        migrations.AddField(
            model_name='label',
            name='level',
            field=models.IntegerField(db_column='label_level', default=1, verbose_name='标签级别'),
        ),
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(db_column='label_name', default='', max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='label',
            name='skill_type',
            field=models.CharField(choices=[('TL', '听力'), ('YD', '阅读'), ('XZ', '写作'), ('KY', '口语')], default='TL', max_length=20, verbose_name='技能分类'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='course_info',
        ),
        migrations.AlterModelTable(
            name='label',
            table='label_dict',
        ),
    ]
